### ISSUE TITLE
Sharing URL on Facebook triggers security check

### ISSUE THREAD

**Issue by HaikuOezu** [ideashower/ShareKit#239]
I have implemented ShareKit on my iOS application and configured Facebook and Twitter sharing accordingly, both work just fine but Facebook sharing has the nasty habit of requiring a captcha every time I try to share an URL, as such.

http://d.pr/9l4Y

I have read somewhere else that a permission to update the stream should be acquired using the "publish_stream" permission, but I'm not sure where to hack in the change or if it would work at all.

**Comment by HaikuOezu** [comment]
OK, apparently Facebook has decided that our entire domain is spammy or something like that so that's the real source of the problem.

**Comment by bgizdov** [comment]
Hi HaikuOezu,

I had the same problem, with totally new domain, nothing spammy. Just used ShareKit to test sharing several times.
After first few times (2-3), Facebook started to give me messages like this url is blocked and spammy.
Now there is no way to post url from that domain in facebook. We tried to contact Facebook, and to unblock our domain, but without success.

Now I am implementing new app with other domain and it started to block my url again, from the first tests.

I am starting to thing the problem comes from ShareKit and then Facebook ban the entire domain.

I think this issue should be reopened.
